train_config:
  model_id_prefix: 'segmentation-model-small-skip-crop'
  dataset_id: 'dataset-small-skip-crop'
  segmentation_model:
    model_name: 'Unet'
    model_parameters:
      backbone_name: 'vgg16'
      encoder_weights: Null
  loss: 'cross_entropy'
  optimizer: 'adam'
  batch_size: 16
  epochs: 5
  training_data_shuffle_seed: 1234
  data_augmentation:
    random_90-degree_rotations: True
