train_config:
  model_id_prefix: 'segmentation-model-fpn-efficientnetb0-study2'
  dataset_id: 'dataset-esrf16_study2_CropCase5_TrnValCaseB'
  segmentation_model:
    model_name: 'FPN' # see models.py for supported versions: 'Unet' 'FPN' 'Linknet'
    model_parameters:
      backbone_name: 'efficientnetb0' #see models.py for supported versions:  'vgg16', 'vgg19', 'resnet18', 'seresnet18', 'resnext50', 'seresnext50', 'inceptionv3', 'mobilenet', 'efficientnetb0'
      encoder_weights: Null   # Null (random initialization) or 'imagenet' (pre-training on ImageNet, only RGB images)
      input_shape: [Null, Null, 1] # [Null, Null, 1] for GV and [Null, Null, 3] for RGB
      activation: 'sigmoid' #tf.keras.activations e.g 'sigmoid', 'softmax', 'linear'
  loss: 'binary_cross_entropy' #'binary_cross_entropy' 'categorical_cross_entropy' 'mean_squared_error' 'mean_absolute_error'
  optimizer: 'adam' # 'adam', 'sdg', 'adagrad', 'adamax', 'ftrl', 'nadam', 'rmsprop'
  batch_size: 8    # FPN model requires batch size of 8 for 1 p100 GPU
  epochs: 100
  training_data_shuffle_seed: 1234
  validation_data_shuffle_seed: 12345
  test_data_shuffle_seed: 123456
  data_augmentation:
    random_90-degree_rotations: True
