train_config:
  model_id_prefix: 'segmentation-model-esrf16_segV1_study1_BinCE_CropCase2_TrnValCaseA'
  dataset_id: 'dataset-esrf16_segV1_study1_CropCase2_TrnValCaseA'
  segmentation_model:
    model_name: 'Unet'
    model_parameters:
      backbone_name: 'vgg16'
      encoder_weights: Null
  loss: 'cross_entropy'
  optimizer: 'adam'
  batch_size: 16    # p100
  epochs: 200
  training_data_shuffle_seed: 1234
  validation_data_shuffle_seed: 12345
  test_data_shuffle_seed: 123456
  data_augmentation:
    random_90-degree_rotations: True